build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  before_script:
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4243,[185.108.78.22]:4243 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFE8IPu1LfB0ePyhgBFTyzXRNBZUiYa1ZaSnkFb746r3MgZQlfMhfxdMtrY3bKoiQ4i+HEUTCUN4BJ5n2PMdGz4=" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts

  script:
    - git clone https://github.com/wybiral/torgo.git
    - cd torgo
    - git checkout a19a6c8a50489e2fdf37223edc5f1284bb965308
    - cd ..
    - mv torgo/ torgo-a19a6c8a50489e2fdf37223edc5f1284bb965308
    - tar zcf torgo-a19a6c8a50489e2fdf37223edc5f1284bb965308.tar.gz torgo-a19a6c8a50489e2fdf37223edc5f1284bb965308
    - mkdir f30 f31
    - fedpkg --release f30 local
    - 'find . -name "*fc30*.rpm" -exec mv {} f30 \;'
    - fedpkg --release f31 local
    - 'find . -name "*fc31*.rpm" -exec mv {} f31 \;'
    - 'scp -r -P4243 f30/* fedora-repo@fedora.autonomia.digital:packages/upload/f30'
    - 'scp -r -P4243 f31/* fedora-repo@fedora.autonomia.digital:packages/upload/f31'
  artifacts:
    paths:
      - 'f30/'
      - 'f31/'
