# Generated by go2rpm 1
%bcond_without check

# https://github.com/wybiral/torgo
%global goipath         github.com/wybiral/torgo
%global commit          a19a6c8a50489e2fdf37223edc5f1284bb965308

%gometa

%global common_description %{expand:
A Golang library for Tor.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Golang library for Tor

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/crypto/ed25519)
BuildRequires:  golang(golang.org/x/crypto/sha3)
BuildRequires:  golang(golang.org/x/net/proxy)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Mar 13 16:35:29 -05 2020 rafael <rafael@autonomia.digital> - 0-0.1.20200313gita19a6c8
- Initial package

